#!/bin/bash
#  usage:  $0 [-t]
#  Pipe a raw email with will-call list attachment to this script, and
#  it will use script/runner to try to integrate it with our main
#  willcall list.
#  -t option means use 'stage' version of app (usually development);
#  otherwise production.

if [ "$1" = "-t" ]; then
    env=development
    dir=stage
else
    env=production
    dir=current
fi
cd /home/audienc/rails/vbo/releases/$dir
# bug: should deduce path to script/runner dir as $ARGV[0]/..
RAILS_ENV=$env ruby script/runner 'EmailGoldstar.receive(STDIN.read)' >/dev/null 2>&1
