---
engines:
  brakeman:
    enabled: true
    exclude_fingerprints:
    - 2f63d663e9f35ba60ef81d56ffc4fbf0660fbc2067e728836176bc18f610f77f
  bundler-audit:
    enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_patterns:
- config/
- db/
- features/
- script/
- spec/
- vendor/
- "app/assets/javascripts/jquery.*.js"
- "app/assets/javascripts/*.min.js"
- "app/assets/javascripts/*.rails.js"
- "app/assets/javascripts/rails.js"
- "app/assets/stylesheets/*"
- "./.*"

