# -*- mode: ruby; -*-
source 'https://rubygems.org'

gem 'acts_as_reportable', '1.1.1'
gem 'builder'
gem 'bundler', '1.3.5'
gem 'constant_contact', '1.4.0'
gem 'dbf', '1.2.8'
gem 'dbi', '0.4.5'
gem 'haml', '3.0.13'
gem 'i18n', '0.4.1'
gem 'mechanize', '1.0.0'
gem 'mysql', '2.8.1'
gem 'nokogiri', '1.4.3.1'
gem 'rails', '2.3.18'
gem 'rake', '>= 10.0.0'
gem 'ruport', '1.6.3'
gem 'stripe', '1.5.16'
# not really development dependencies, but 'rake' needs them 
gem 'rdoc'
gem 'rspec', '~> 1.3'

group :development, :test do
  # cucumber and capybara
  gem 'ruby-debug'
  gem 'ZenTest'
  gem 'autotest-fsevent'
  gem 'capistrano', '2.5.10'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'chronic'
  gem 'factory_girl', '~> 2.6.4'
  gem 'timecop'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'fakeweb'
  gem 'launchy'
  gem 'rack-test'
  gem 'rspec-rails'
  gem 'test-unit', '1.2.3'
end
