<%
common = %q{-m -i --require features --color --tags 'not @suspended'}
%>
default:    <%= common %> --format pretty --format rerun --out tmp/rerun-<%= Time.now.to_i % 1_000_000 %>.txt --publish
ci-report:  <%= common %> --retry 3 --format pretty  --publish
ci:         <%= common %> --retry 3 --quiet  --format summary
no_javascript: <%= common %> --tags 'not @javascript'
javascript: <%= common %> --tags '@javascript'
cur:        <%= common %> --tags @cur
